'use strict';

const DEFAULT_COUNT = 1;
const MAX_PUBLICATION_COUNT = 1000;
const MAX_ID_LENGTH = 6;
const MAX_COMMENTS_COUNT = 4;

module.exports = {
  DEFAULT_COUNT,
  MAX_PUBLICATION_COUNT,
  MAX_ID_LENGTH,
  MAX_COMMENTS_COUNT,
};
